project:
  type: website

website:
  title: "MIGUELCUBEROGOMEZ.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Eda.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



