project:
  type: website

website:
  title: "MIGUELCUBEROGOMEZ.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Eda.qmd
        text: Exploratory Data Analysis
      - href: clusters.qmd
        text: Clusters
      - href: Rainprediction.qmd
        text: Rain Prediction
      - href: zumonaranjas.qmd
        text: Zumo de Naranjas
      - href: TFG.qmd
        text: TFG
        
format:
  html:
    theme: journal
    css: styles.css
    toc: true



